// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlowTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ValidacaoDeFuncionalidadesDoSiteDosCorreiosFeature : object, Xunit.IClassFixture<ValidacaoDeFuncionalidadesDoSiteDosCorreiosFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Correios.feature"
#line hidden
        
        public ValidacaoDeFuncionalidadesDoSiteDosCorreiosFeature(ValidacaoDeFuncionalidadesDoSiteDosCorreiosFeature.FixtureData fixtureData, SpecFlowTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Validacao de funcionalidades do site dos Correios", "    Como usuario do site dos Correios\r\n    Eu quero buscar CEPs e rastrear objeto" +
                    "s\r\n    Para confirmar que as funcionalidades estao operando corretamente", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
    #line hidden
#line 8
        testRunner.Given("que estou no site dos Correios", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 9
        testRunner.And("aceito os cookies se existirem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="01 - Buscar CEP invalido deve retornar mensagem de erro")]
        [Xunit.TraitAttribute("FeatureTitle", "Validacao de funcionalidades do site dos Correios")]
        [Xunit.TraitAttribute("Description", "01 - Buscar CEP invalido deve retornar mensagem de erro")]
        [Xunit.TraitAttribute("Category", "Ordem1")]
        [Xunit.TraitAttribute("Category", "CEP")]
        [Xunit.TraitAttribute("Category", "Invalido")]
        [Xunit.TraitAttribute("Category", "ID")]
        public void _01_BuscarCEPInvalidoDeveRetornarMensagemDeErro()
        {
            string[] tagsOfScenario = new string[] {
                    "Ordem1",
                    "CEP",
                    "Invalido",
                    "ID"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 - Buscar CEP invalido deve retornar mensagem de erro", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 13
        testRunner.When("eu navego para a pagina de busca de CEP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 14
        testRunner.And("preencho o campo de CEP com \"80700000\" usando seletor ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 15
        testRunner.And("preencho o captcha manualmente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 16
        testRunner.And("clico no botao Buscar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 17
        testRunner.Then("devo ver a mensagem \"Nao ha dados a serem exibidos\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
#line 18
        testRunner.And("devo ver o titulo \"Dados nao encontrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="02 - Buscar CEP valido deve retornar endereco correto")]
        [Xunit.TraitAttribute("FeatureTitle", "Validacao de funcionalidades do site dos Correios")]
        [Xunit.TraitAttribute("Description", "02 - Buscar CEP valido deve retornar endereco correto")]
        [Xunit.TraitAttribute("Category", "Ordem2")]
        [Xunit.TraitAttribute("Category", "CEP")]
        [Xunit.TraitAttribute("Category", "Valido")]
        [Xunit.TraitAttribute("Category", "XPath")]
        public void _02_BuscarCEPValidoDeveRetornarEnderecoCorreto()
        {
            string[] tagsOfScenario = new string[] {
                    "Ordem2",
                    "CEP",
                    "Valido",
                    "XPath"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 - Buscar CEP valido deve retornar endereco correto", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 22
        testRunner.When("eu navego para a pagina de busca de CEP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 23
        testRunner.And("preencho o campo de CEP com \"01013001\" usando seletor ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 24
        testRunner.And("preencho o captcha manualmente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 25
        testRunner.And("clico no botao Buscar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 26
        testRunner.Then("o resultado deve conter \"Rua Quinze de Novembro\" usando seletor XPath", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
#line 27
        testRunner.And("o resultado deve conter \"Sao Paulo\" usando seletor XPath", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="03 - Buscar rastreamento invalido deve retornar mensagem de nao encontrado")]
        [Xunit.TraitAttribute("FeatureTitle", "Validacao de funcionalidades do site dos Correios")]
        [Xunit.TraitAttribute("Description", "03 - Buscar rastreamento invalido deve retornar mensagem de nao encontrado")]
        [Xunit.TraitAttribute("Category", "Ordem3")]
        [Xunit.TraitAttribute("Category", "Rastreamento")]
        [Xunit.TraitAttribute("Category", "Invalido")]
        [Xunit.TraitAttribute("Category", "CSS")]
        public void _03_BuscarRastreamentoInvalidoDeveRetornarMensagemDeNaoEncontrado()
        {
            string[] tagsOfScenario = new string[] {
                    "Ordem3",
                    "Rastreamento",
                    "Invalido",
                    "CSS"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 - Buscar rastreamento invalido deve retornar mensagem de nao encontrado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 31
        testRunner.When("eu navego para a pagina de rastreamento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 32
        testRunner.And("preencho o campo de codigo com \"SS987654321BR\" usando seletor CSS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 33
        testRunner.And("preencho o captcha manualmente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 34
        testRunner.And("clico no botao Consultar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 35
        testRunner.Then("devo ver a mensagem \"Objeto nao encontrado na base\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
#line 36
        testRunner.And("clico no botao OK para fechar o modal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ValidacaoDeFuncionalidadesDoSiteDosCorreiosFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ValidacaoDeFuncionalidadesDoSiteDosCorreiosFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
