// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace technicaltest_b3.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ValidacaoDeCEPERastreamentoDosCorreiosFeature : object, Xunit.IClassFixture<ValidacaoDeCEPERastreamentoDosCorreiosFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Correios.feature"
#line hidden
        
        public ValidacaoDeCEPERastreamentoDosCorreiosFeature(ValidacaoDeCEPERastreamentoDosCorreiosFeature.FixtureData fixtureData, technicaltest_b3_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Validação de CEP e Rastreamento dos Correios", "    Como usuário do site dos Correios\r\n    Eu quero consultar CEPs e rastrear enc" +
                    "omendas\r\n    Para obter informações de endereços e status de entregas", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
#line 8
    testRunner.Given("que eu estou no site dos Correios", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 9
    testRunner.And("eu aceito os cookies se aparecerem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Consultar CEP inválido deve retornar mensagem de erro")]
        [Xunit.TraitAttribute("FeatureTitle", "Validação de CEP e Rastreamento dos Correios")]
        [Xunit.TraitAttribute("Description", "Consultar CEP inválido deve retornar mensagem de erro")]
        [Xunit.TraitAttribute("Category", "CEP")]
        [Xunit.TraitAttribute("Category", "Negativo")]
        public void ConsultarCEPInvalidoDeveRetornarMensagemDeErro()
        {
            string[] tagsOfScenario = new string[] {
                    "CEP",
                    "Negativo"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Consultar CEP inválido deve retornar mensagem de erro", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 13
    testRunner.When("eu navego para a página de busca de CEP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 14
    testRunner.And("eu preencho o CEP \"80700000\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 15
    testRunner.And("eu preencho o captcha manualmente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 16
    testRunner.And("eu clico no botão de buscar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 17
    testRunner.Then("devo ver a mensagem \"Não há dados a serem exibidos\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 18
    testRunner.And("devo ver o título \"Dados não encontrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Consultar CEP válido deve retornar o endereço correto")]
        [Xunit.TraitAttribute("FeatureTitle", "Validação de CEP e Rastreamento dos Correios")]
        [Xunit.TraitAttribute("Description", "Consultar CEP válido deve retornar o endereço correto")]
        [Xunit.TraitAttribute("Category", "CEP")]
        [Xunit.TraitAttribute("Category", "Positivo")]
        public void ConsultarCEPValidoDeveRetornarOEnderecoCorreto()
        {
            string[] tagsOfScenario = new string[] {
                    "CEP",
                    "Positivo"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Consultar CEP válido deve retornar o endereço correto", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 22
    testRunner.When("eu navego para a página de busca de CEP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 23
    testRunner.And("eu preencho o CEP \"01013001\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 24
    testRunner.And("eu preencho o captcha manualmente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 25
    testRunner.And("eu clico no botão de buscar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 26
    testRunner.Then("devo ver o logradouro \"Rua Quinze de Novembro\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 27
    testRunner.And("devo ver a cidade/estado \"São Paulo/SP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Consultar código de rastreamento inválido deve retornar mensagem de erro")]
        [Xunit.TraitAttribute("FeatureTitle", "Validação de CEP e Rastreamento dos Correios")]
        [Xunit.TraitAttribute("Description", "Consultar código de rastreamento inválido deve retornar mensagem de erro")]
        [Xunit.TraitAttribute("Category", "Rastreamento")]
        [Xunit.TraitAttribute("Category", "Negativo")]
        public void ConsultarCodigoDeRastreamentoInvalidoDeveRetornarMensagemDeErro()
        {
            string[] tagsOfScenario = new string[] {
                    "Rastreamento",
                    "Negativo"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Consultar código de rastreamento inválido deve retornar mensagem de erro", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 31
    testRunner.When("eu navego para a página de rastreamento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 32
    testRunner.And("eu preencho o código de rastreio \"SS987654321BR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 33
    testRunner.And("eu preencho o captcha manualmente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 34
    testRunner.And("eu clico no botão de consultar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 35
    testRunner.Then("devo ver a mensagem \"Objeto não encontrado na base\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Fluxo completo - CEP inválido, CEP válido e Rastreamento inválido")]
        [Xunit.TraitAttribute("FeatureTitle", "Validação de CEP e Rastreamento dos Correios")]
        [Xunit.TraitAttribute("Description", "Fluxo completo - CEP inválido, CEP válido e Rastreamento inválido")]
        [Xunit.TraitAttribute("Category", "FluxoCompleto")]
        [Xunit.TraitAttribute("Category", "E2E")]
        public void FluxoCompleto_CEPInvalidoCEPValidoERastreamentoInvalido()
        {
            string[] tagsOfScenario = new string[] {
                    "FluxoCompleto",
                    "E2E"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Fluxo completo - CEP inválido, CEP válido e Rastreamento inválido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 40
    testRunner.When("eu navego para a página de busca de CEP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 41
    testRunner.And("eu preencho o CEP \"80700000\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 42
    testRunner.And("eu preencho o captcha manualmente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 43
    testRunner.And("eu clico no botão de buscar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 44
    testRunner.Then("devo ver a mensagem \"Não há dados a serem exibidos\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 47
    testRunner.Given("que eu volto para a página inicial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 48
    testRunner.When("eu navego para a página de busca de CEP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 49
    testRunner.And("eu preencho o CEP \"01013001\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 50
    testRunner.And("eu preencho o captcha manualmente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 51
    testRunner.And("eu clico no botão de buscar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 52
    testRunner.Then("devo ver o logradouro \"Rua Quinze de Novembro\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 53
    testRunner.And("devo ver a cidade/estado \"São Paulo/SP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 56
    testRunner.Given("que eu volto para a página inicial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 57
    testRunner.When("eu navego para a página de rastreamento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 58
    testRunner.And("eu preencho o código de rastreio \"SS987654321BR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 59
    testRunner.And("eu preencho o captcha manualmente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 60
    testRunner.And("eu clico no botão de consultar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 61
    testRunner.Then("devo ver a mensagem \"Objeto não encontrado na base\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Consultar diferentes CEPs")]
        [Xunit.TraitAttribute("FeatureTitle", "Validação de CEP e Rastreamento dos Correios")]
        [Xunit.TraitAttribute("Description", "Consultar diferentes CEPs")]
        [Xunit.TraitAttribute("Category", "CEP")]
        [Xunit.TraitAttribute("Category", "DataDriven")]
        [Xunit.InlineDataAttribute("80700000", "Não há dados a serem exibidos", new string[0])]
        [Xunit.InlineDataAttribute("01013001", "Rua Quinze de Novembro - São Paulo/SP", new string[0])]
        [Xunit.InlineDataAttribute("00000000", "Não há dados a serem exibidos", new string[0])]
        public void ConsultarDiferentesCEPs(string cep, string resultado, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CEP",
                    "DataDriven"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("cep", cep);
            argumentsOfScenario.Add("resultado", resultado);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Consultar diferentes CEPs", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 65
    testRunner.When("eu navego para a página de busca de CEP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 66
    testRunner.And(string.Format("eu preencho o CEP \"{0}\"", cep), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 67
    testRunner.And("eu preencho o captcha manualmente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 68
    testRunner.And("eu clico no botão de buscar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 69
    testRunner.Then(string.Format("o resultado deve ser \"{0}\"", resultado), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ValidacaoDeCEPERastreamentoDosCorreiosFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ValidacaoDeCEPERastreamentoDosCorreiosFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
